# Copyright 2017 The Openstack-Helm Authors.
#
# Licensed under the Apache License, Version 2.0 (the 'License');
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an 'AS IS' BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values for fluentbit.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

release_group: null

labels:
  fluentd:
    node_selector_key: openstack-control-plane
    node_selector_value: enabled
  fluentbit:
    node_selector_key: openstack-control-plane
    node_selector_value: enabled

images:
  tags:
    fluentbit: docker.io/fluent/fluent-bit:0.12.9
    fluentd: docker.io/kolla/ubuntu-source-fluentd:ocata
    dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
    helm_tests: docker.io/kolla/ubuntu-source-kolla-toolbox:3.0.3
    image_repo_sync: docker.io/docker:17.07.0
  pull_policy: IfNotPresent
  local_registry:
    active: false
    exclude:
      - dep_check
      - image_repo_sync

dependencies:
  image_repo_sync:
    services:
      - service: local_image_registry
        endpoint: internal
  fluentd:
    services:
    - service: elasticsearch
      endpoint: internal
  fluentd_with_kafka:
    services:
    - service: elasticsearch
      endpoint: internal
    - service: kafka
      endpoint: public
  fluentbit:
    services:
    - service: aggregator
      endpoint: internal
  tests:
    services:
    - service: elasticsearch
      endpoint: internal
    - service: aggregator
      endpoint: internal

conditional_dependencies:
  local_image_registry:
    jobs:
      - fluent-logging-image-repo-sync
    services:
      - service: local_image_registry
        endpoint: node
  fluentd:
    services:
      - service: kafka
        endpoint: public


conf:
  fluentbit:
    service:
      log_level: info
    input:
      mem_buf_limit: 5MB
    override:
  fluentd:
    kafka:
      enabled: false
      topic_name: logs
      flush_interval: 3s
      output_data_type: json
    elasticsearch:
      logstash: true
      buffer_chunk_limit: 10M
      buffer_queue_limit: 32
      flush_interval: 15s
      max_retry_wait: 300
      disable_retry_limit: true
      num_threads: 8
    override:

endpoints:
  cluster_domain_suffix: cluster.local
  elasticsearch:
    namespace: null
    name: elasticsearch
    hosts:
      data: elasticsearch-data
      default: elasticsearch-logging
      discovery: elasticsearch-discovery
      public: elasticsearch
    host_fqdn_override:
      default: null
    path:
      default: null
    scheme:
      default: http
    port:
      client:
        default: 9200
      discovery:
        default: 9300
  kafka:
    namespace: null
    name: kafka
    hosts:
      default: kafka-logging
      public: kafka
    scheme:
      default: http
      public: http
    port:
      service:
        default: 9092
  aggregator:
    namespace: null
    name: fluentd
    hosts:
      default: fluentd-logging
      internal: fluentd-logging
    scheme:
      default: http
    port:
      service:
        default: 24224
        internal: 24224
    host_fqdn_override:
      default: null

network:
  fluentd:
    node_port:
      enabled: false
      port: 32329
    port: 24224

pod:
  affinity:
      anti:
        type:
          default: preferredDuringSchedulingIgnoredDuringExecution
        topologyKey:
          default: kubernetes.io/hostname
  lifecycle:
    upgrades:
      daemonsets:
        pod_replacement_strategy: RollingUpdate
        fluentbit:
          enabled: true
          min_ready_seconds: 0
          max_unavailable: 1
      deployments:
        revision_history: 3
        pod_replacement_strategy: RollingUpdate
        rolling_update:
          max_unavailable: 1
          max_surge: 3
    termination_grace_period:
      fluentd_aggregator:
        timeout: 30
  resources:
    fluentbit:
      enabled: false
      limits:
        memory: '400Mi'
        cpu: '400m'
      requests:
        memory: '100Mi'
        cpu: '100m'
    fluentd:
      enabled: false
      limits:
        memory: '1024Mi'
        cpu: '2000m'
      requests:
        memory: '128Mi'
        cpu: '500m'
    jobs:
      tests:
        limits:
          memory: '1024Mi'
          cpu: '2000m'
        requests:
          memory: '128Mi'
          cpu: '100m'
  replicas:
    fluentd: 3
  mounts:
    fluentd:
      fluentd:
    fluentbit:
      fluentbit:
    fluent_tests:
      fluent_tests:

manifests:
  service_fluentd: true
  deployment_fluentd: true
  daemonset_fluentbit: true
  job_image_repo_sync: true
  helm_tests: true
  configmap_bin: true
  configmap_etc: true
  clusterrole: true
  clusterrolebinding: true
  rbac_entrypoint: true
  serviceaccount: true
