# Copyright 2017 The Openstack-Helm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values for kube-state-metrics.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

images:
  tags:
    openstack_metrics_exporter: docker.io/rakeshpatnaik/prometheus-openstack-exporter:v0.1
    helm_tests: docker.io/kolla/ubuntu-source-kolla-toolbox:3.0.3
    pull_policy: IfNotPresent
    dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
    image_repo_sync: docker.io/docker:17.07.0
  pull_policy: IfNotPresent
  local_registry:
    active: false
    exclude:
      - dep_check
      - image_repo_sync

labels:
  node_selector_key: openstack-control-plane
  node_selector_value: enabled

pod:
  affinity:
      anti:
        type:
          default: preferredDuringSchedulingIgnoredDuringExecution
        topologyKey:
          default: kubernetes.io/hostname
  mounts:
    openstack_metrics_exporter:
      openstack_metrics_exporter:
      init_container: null
  replicas:
    openstack_metrics_exporter: 1
  lifecycle:
    upgrades:
      revision_history: 3
      pod_replacement_strategy: RollingUpdate
      rolling_update:
        max_unavailable: 1
        max_surge: 3
    termination_grace_period:
      openstack_metrics_exporter:
        timeout: 30
  resources:
    enabled: false
    kube_state_metrics:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "1024Mi"
        cpu: "2000m"
    jobs:
      image_repo_sync:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "1024Mi"
          cpu: "2000m"

secrets:
  identity:
    user: openstack-metrics-user

dependencies:
  image_repo_sync:
    services:
      - service: local_image_registry
        endpoint: internal

conditional_dependencies:
  local_image_registry:
    jobs:
      - openstack-metrics-exporter-image-repo-sync
    services:
      - service: local_image_registry
        endpoint: node

conf:
  openstack_metrics_exporter:
    polling_interval_seconds: 30
    timeout_seconds: 20
    retries: 1
    os_cpu_oc_ratio: 1.5
    os_ram_oc_ratio: 1.0

endpoints:
  cluster_domain_suffix: cluster.local
  local_image_registry:
    name: docker-registry
    namespace: docker-registry
    hosts:
      default: localhost
      internal: docker-registry
      node: localhost
    host_fqdn_override:
      default: null
    port:
      registry:
        node: 5000
  openstack_metrics_exporter:
    namespace: null
    hosts:
      default: openstack-metrics
    host_fqdn_override:
      default: null
    path:
      default: null
    scheme:
      default: 'http'
    scrape: true
  identity:
    name: keystone
    auth:
      user:
        role: admin
        region_name: RegionOne
        username: nova
        password: password
        project_name: service
        user_domain_name: default
        project_domain_name: default
    hosts:
      default: keystone-api
      public: keystone
    host_fqdn_override:
      default: null
    path:
      default: /v3
    scheme:
      default: 'http'
    port:
      admin:
        default: 35357
      api:
        default: 80

network:
  openstack_metrics_exporter:
    port: 9103

manifests:
  configmap_bin: true
  clusterrole: true
  clusterrolebinding: true
  deployment: true
  job_image_repo_sync: true
  rbac_entrypoint: true
  service_openstack_metrics_exporter: true
  serviceaccount: true
  openstack_metrics_user: true
