# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: "creating directory for helm release descriptions"
  file:
    path: "{{ logs_dir }}/prometheus"
    state: directory

- name: "get exporter services in kube-system namespace"
  shell: |-
          set -e
          kubectl get svc -l component=metrics -n kube-system -o json \
            | jq -r '.items[].metadata.name'
  args:
    executable: /bin/bash
  register: kube_system_exporters

- include: util-common-prom-metrics.yaml
  vars:
    exporter: "{{ kube_system_exporter }}"
    namespace: kube-system
  loop_control:
    loop_var: kube_system_exporter
  with_items: "{{ kube_system_exporters.stdout_lines }}"

- name: "get exporter services in openstack namespace"
  shell: |-
          set -e
          kubectl get svc -l component=metrics -n openstack -o json \
            | jq -r '.items[].metadata.name'
  args:
    executable: /bin/bash
  register: openstack_exporters

- include: util-common-prom-metrics.yaml
  vars:
    exporter: "{{ openstack_exporter }}"
    namespace: openstack
  loop_control:
    loop_var: openstack_exporter
  with_items: "{{ openstack_exporters.stdout_lines }}"

- name: "Downloads logs to executor"
  synchronize:
    src: "{{ logs_dir }}/prometheus"
    dest: "{{ zuul.executor.log_root }}/{{ inventory_hostname }}"
    mode: pull
  ignore_errors: True
