# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Kubectl describe all namespaced objects common block
  vars:
    api_objects:
      - pod
      - service
      - pvc
      - deployment
      - statefulset
      - daemonset
      - serviceaccount
      - endpoints
    namespace: null

  block:
    - name: "Describe all {{ api_object }} objects in {{ namespace }} namespace"
      vars:
        object_namespace: "{{ namespace }}"
        api_object: "{{ api_object }}"
      loop_control:
        loop_var: api_object
      include: util-common-namespace-describe.yaml
      with_items: "{{ api_objects }}"
